### ISSUE TITLE
@ForeignKey does not always work

### ISSUE THREAD

**Issue by blackat** [hibernate/hibernate-jpa-api#6]
Hi,
do you have some news about this issue please?
https://hibernate.atlassian.net/browse/HHH-9591

I have a similar issue, Hibernate does not generate the specified foreign key and I would know if there is at least a temporary workaround.

Thanks a lot for the attention.

Update:
as workaround I am using the hibernate deprecated annotation
@org.hibernate.annotations.ForeignKey(name = "FK_COLUMN_X")

**Comment by brmeyer** [comment]
Please comment directly on the JIRA, rather than open new issues...
